version: '3.7'

services:
  devcontainer:
    image: acme/orderservice-dev-container:0.1
    build: .
    container_name: orderservice-dev-container
    hostname: orderservice-dev.local
    working_dir: /src
    volumes:
       - ..:/src
       # Allow AWS CLI and other tools to read an AWS profile
       - ~/.aws:/home/node/.aws
    command: sleep infinity
